# Generated by Django 3.2.9 on 2021-11-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_book_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='review',
            field=models.TextField(null=True),
        ),
    ]
