# Generated by Django 3.2.9 on 2021-11-09 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_borrow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrow',
            old_name='pub_date',
            new_name='date',
        ),
    ]
