# Generated by Django 3.2.9 on 2021-11-09 06:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lms', '0007_rename_pub_date_borrow_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Borrow',
            new_name='RequestBook',
        ),
    ]
