# Generated by Django 3.2.9 on 2021-11-09 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0008_rename_borrow_requestbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestbook',
            name='book',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='requestbook',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
