# Generated by Django 3.2.9 on 2021-11-12 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0011_alter_borrow_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrow',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='borrow',
            name='return_date',
        ),
        migrations.RemoveField(
            model_name='borrow',
            name='start_date',
        ),
        migrations.AddField(
            model_name='borrow',
            name='is_returned',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
