# Generated by Django 3.2.9 on 2021-11-12 09:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0012_auto_20211112_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 12, 16, 8, 53, 127473)),
        ),
        migrations.AddField(
            model_name='borrow',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
