# Generated by Django 3.2.9 on 2021-12-11 09:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0014_auto_20211112_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 9, 16, 20, 58, 720316)),
        ),
        migrations.AlterUniqueTogether(
            name='requestbook',
            unique_together={('user', 'book')},
        ),
    ]
