# Generated by Django 3.2.9 on 2021-12-11 11:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0015_auto_20211211_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 9, 18, 54, 35, 888471)),
        ),
        migrations.AlterUniqueTogether(
            name='requestbook',
            unique_together=set(),
        ),
    ]
