# Generated by Django 3.2.9 on 2022-01-06 07:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0020_auto_20220103_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='available',
            name='nota',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 7, 14, 24, 19, 666945)),
        ),
    ]
