# Generated by Django 3.2.9 on 2022-01-06 07:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0022_auto_20220106_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 7, 14, 44, 16, 93038)),
        ),
    ]
