# Generated by Django 3.2.9 on 2022-01-06 07:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0023_alter_borrow_end_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Available',
        ),
        migrations.AddField(
            model_name='book',
            name='avai',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 7, 14, 55, 55, 264586)),
        ),
    ]
