# Generated by Django 3.2.9 on 2022-01-07 05:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0024_auto_20220106_1455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='avai',
            new_name='bring',
        ),
        migrations.AlterField(
            model_name='borrow',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 8, 12, 27, 35, 776352)),
        ),
    ]
