# Generated by Django 3.2.9 on 2022-01-12 08:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0026_auto_20220107_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bring',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='order',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 13, 15, 3, 16, 368549)),
        ),
    ]
